[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
colorscheme = "gruvbox"
background = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true 
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
statusline_separator = "nil"
statusline_inactive_separator = "bar"
buffer_index_type = 4
windows_index_type = 3
enable_tabline_filetype_icon = false
enable_statusline_display_mode = false
statusline_unicode_symbols = false
# Enable vim compatible mode, avoid changing origin vim key bindings
vimcompatible = true
bootstrap_before = "config#before"
bootstrap_after = "config#after"
#syncheck
enable_neomake = false
enable_ale =  true 
enable_ycm = false


# Enable autocomplete layer
 
[[layers]]
name = 'deoplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "cycle"
auto-completion-complete-with-key-sequence = "<v-m>"
auto-completion-delay = 200000


[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#c"
enable = false

[[layers]]
name = 'tags'


[[custom_plugins]]
name = "Yggdroot/LeaderF"
merged = 0

[[custom_plugins]]
name = "kien/ctrlp.vim"
merged = 0

[[custom_plugins]]
name = "Valloric/YouCompleteMe"
merged = 0

[[custom_plugins]]
name = "mileszs/ack.vim"
merged = 0

[[custom_plugins]]
name = "wsdjeg/FlyGrep.vim"
merged = 0

[[custom_plugins]]
name = "mbriggs/mark.vim"
merged = 0

[[custom_plugins]]
name = "rdnetto/YCM-Generator"
merged = 0
